API_KEY = 'PKEU4WXQTBJBKMAUO39E'
SECRET_KEY = 'v4Rmv0OlYQzPh4yHtXR67aKbUv1Svs3w1xDDrub8'

SYMBOL = 'ETH/USD'
POSITION_SIZE = 0.001

# gridbot settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 3

CHECK_ORDERS_FREQUENCY = 2
CLOSED_ORDER_STATUS = "closed"




